# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Lab 3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:    
  lab_3_python_311:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd 3_lab
        if [ -f Pipfile ]; then pipenv install --system --dev; fi

    - name: Lint with flake8
      run: |
        cd 3_lab
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest and CodeCov
      run: |
        cd 3_lab
        coverage run -m pytest -vra test.py
        coverage xml
        echo "Всі тести пройшли успішно!"
    
    - name: Codecov
      uses: codecov/codecov-action@v4.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: BobasB/2024_kn320_test_nm
        directory: 3_lab/
